name=M5Unit-INFRARED
version=0.2.0
author=M5Stack
maintainer=M5Stack
sentence=Library for M5Stack UNIT INFRARED using M5UnitUnified
paragraph=Supports TMOS PIR (SKU:U185), PIR (SKU:U004/U054), OP photointerrupter (SKU:U057/U058), and IR remote (SKU:U002).
category=Device Control
url=https://github.com/m5stack/M5Unit-INFRARED
architectures=esp32
includes=M5UnitUnifiedINFRARED.h
depends=M5UnitUnified,M5Utility,M5HAL
